spring.application.name=crud-empleados-spring-mvc
# server.port=${PORT:8080}

# ===============================
# = DATA SOURCE
# ===============================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/crud-empleados-spring-mvc
# spring.datasource.url=jdbc:mysql://noorstitches?useLegacyDatetimeCode=false&serverTimezone=Europe/Madrid
spring.datasource.username=root
spring.datasource.password=Temp2025

# ===============================
# = JPA / HIBERNATE
# ===============================

# Configuracion para Hibernate (ORM) (Object Relational Mapping) 
# Es un componente que permite hacer consultas a las entidades
# Las entidades son las clases de Java, con la anotación "@Entity"
# que estan mapeadas o relacionadas con las tablas de la base de datos.
# Hibernate traduce las consultas a las entidades, a consultas SQL
# que envia al motor (engine) de base de datos.

# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# dml + ddl (sentencias de crear objetos en SQL: tablas, procedures, vistas)
# create-drop -> se crean las tablas en BBDD y se borran cuando el server de Tomcat se inicia y se cierra
spring.jpa.hibernate.ddl-auto=create-drop 
spring.jpa.show-sql=true
