spring.application.name=crud-empleados-spring-mvc
server.port=${PORT:8080}

# ===============================
# = DATA SOURCE
# ===============================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://mainline.proxy.rlwy.net:28402/crud-empleados-spring-mvc
# spring.datasource.url=jdbc:mysql://mainline.proxy.rlwy.net:28402/noorstitches?useLegacyDatetimeCode=false&serverTimezone=Europe/Madrid
spring.datasource.username=root
spring.datasource.password=Temp2025
# ===============================
# = JPA / HIBERNATE
# ===============================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
